version: '3'
services:
  api:
    image: lottery-api
    build: .
    networks:
      - backend
    ports:
      - "3030:3030"

  web-cli:
    image: lottery-api
    networks:
      - backend
    command: sh

networks:
  backend:
    driver: bridge